site_name: 'EIPL: Embodied Intelligence with Deep Predictive Learning'
site_description: EIPL User Guide, Japanese version
site_author: Hiroshi Ito
site_url: https://ogata-lab.github.io/eipl-docs/en/
repo_url: https://github.com/ogata-lab/eipl/
copyright: 'Copyright &copy; 2023 Ogata Laboratory, Waseda University'
nav:
  - 'Introduction': 'index.md'
  - 'Deep Predictive Learning': 'overview.md'
  - 'Set Up':
    - 'Install': 'install/install-software.md'
    - 'Quick Start': 'install/quick-start.md'
  - 'Motion Teaching':
    - 'Overview': 'teach/overview.md'
    - 'Setup': 'teach/setup.md'
    - 'Generate Dataset': 'teach/dataset.md'
  - 'Train Model':
    - 'Dataloader': 'model/dataloader.md'
    - 'Model Implementation': 'model/SARNN.md'
    - 'Train': 'model/train.md'
    - 'Inference': 'model/test.md'
  - 'Robot Simulator':
    - 'Motion Teaching': 'simulator/dataset.md'
    - 'Model Training': 'simulator/train.md'
    - 'Motion Generation': 'simulator/rt_control.md'
  - 'Real Robot':
    - 'Overview': 'robot/overview.md'
  - 'Model Zoo':
    - 'Overview': 'zoo/overview.md'
    - 'MTRNN': 'zoo/MTRNN.md'
    - 'CAE-RNN': 'zoo/CAE-RNN.md'
    - 'CNNRNN': 'zoo/CNNRNN.md'
  - 'Tips and Tricks':
    - 'Pre-process': 'tips/normalization.md'
    - 'Image Augmentation': 'tips/augmentation.md'
  - 'FAQ': 'faq.md'
  - 'License': 'license.md'

theme:
  name: material
  favicon: 'img/favicon.ico'
  logo: 'img/logo.svg'
  language: 'en'
  features:
    - toc.integrate
extra:
  analytics:
    provider: google
    property: G-J6RG9X05HL
  alternate:
    - name: 'English'
      link: 'https://ogata-lab.github.io/eipl-docs/en/'
    - name: '日本語'
      link: 'https://ogata-lab.github.io/eipl-docs/ja/'

markdown_extensions:
  - tables
  - attr_list
  - footnotes
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - def_list

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [./docs/model/src/,./docs/zoo/src/]
          options:
            docstring_style: google
  - search:
      lang: en
  - bibtex:
      bib_file: "./assets/refs.bib"

extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  
extra_css:
  - css/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
