site_name: 'EIPL: Embodied Intelligence with Deep Predictive Learning'
site_description: EIPL User Guide, Japanese version
site_author: Hiroshi Ito
site_url: https://ogata-lab.github.io/eipl/
copyright: 'Copyright &copy; 2023 Ogata Laboratory, Waseda University'

theme:
  name: 'material'
  favicon: 'html/resources/favicon.ico'
  logo: 'html/resources/logo.svg'
  palette:
    primary: 'red'

markdown_extensions:
  - admonition

plugins:
  - redirects:
      redirect_maps:
        'index.md': 'https://ogata-lab.github.io/eipl-docs/top/'

extra:
  analytics:
    provider: google
    property: G-J6RG9X05HL    
